version: '3.8'

services:
  todo-db:
    image: postgres:15
    container_name: todo-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: todo_db
    ports:
      - "5434:5432"
    volumes:
      - todo-db-data:/var/lib/postgresql/data
    networks:
      - my-shared-network

  migrate:
    image: migrate/migrate
    container_name: todo-migrate
    command: -path /app/migrations -database "postgres://postgres:${DB_PASSWORD}@todo-db:5432/todo_db?sslmode=disable" up
    volumes:
      - ./migrations:/app/migrations
    depends_on:
      - todo-db
    networks:
      - my-shared-network

  todo-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-service
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: todo-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: todo_db
    ports:
      - "8082:8082"
    depends_on:
      - todo-db
      - migrate
    networks:
      - my-shared-network

volumes:
  todo-db-data:

networks:
  my-shared-network:
    external: true
